version: "3"
services:
  xvfb:
    build: ./xvfb
    ports:
      - "6001:6001"
      - "6000:6000"
      - "5900:5900"
  playground:
    build: ./playground
    depends_on:
      - xvfb
    environment:
      - DISPLAY="xvfb:0.0"
