version: "3"
services:
  xvfb:
    build: ./xvfb
    ports:
      - "6000:6000"
      - "5900:5900"
    command: "/entrypoint.sh"
  chrome:
    build: ./chrome
    depends_on:
      - xvfb
    environment:
      - DISPLAY=xvfb:0
    command: "/entrypoint.sh"
